name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build (${{ matrix.os-name }})
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-name: MacOS ARM64
            runner: macos-latest
            cmake-preset: ""
            artifact-name: dynamics-macos-arm64
          - os-name: Windows x86_64
            runner: windows-latest
            cmake-preset: ""
            artifact-name: dynamics-windows-x64
          - os-name: Ubuntu x86_64
            runner: ubuntu-latest
            cmake-preset: ""
            artifact-name: dynamics-linux-x64
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update -y
          # Wayland
          sudo apt install -y libwayland-dev wayland-protocols libwayland-bin
          # X11
          sudo apt install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Setup CMake 4.2.x
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "~4.2"
          
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Package app bundle (macOS)
        if: runner.os == 'macOS'
        run: |
          APP_PATH="build/out/dynamics.app"
          ZIP_NAME="${{ matrix.artifact-name }}.zip"
          ditto -c -k --keepParent "$APP_PATH" "$ZIP_NAME"

      - name: Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-name }}.zip
          if-no-files-found: error

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/out/Release/dynamics.exe
          if-no-files-found: error


      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/out/dynamics
          if-no-files-found: error
